apiVersion: v1
kind: Pod
metadata:
  name: worker1
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: worker2
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Pod
metadata:
  name: master
spec:
  containers:
    - name: mysql
      image: mysql:latest
      ports:
        - containerPort: 3306

